Update Website to 2023
leapfrogtechnology/frogtoberfest pull request #68
Opened 2023-09-26 08:23 UTC by RikLakhe

1. Update Routes
2. Added Images for 2023 Frogtober

2023-09-27 13:36 UTC, bhattaraib58 requested changes
Please separate out into managable PRs.
E.g: 
1. Sass implementation 
2. Assests Add
3. Main feature

2023-09-28 03:21 UTC, shakyaprasen requested changes
Do we need all the scss utilities? I do not think each and every utility is being used. Please try to reduce code.

Maybe we can use something like purgecss to remove unused css as I think we might be shipping too many classes.

2023-09-28 03:21 UTC, shakyaprasen commented on public/assets/scripts.js
> +document.addEventListener('DOMContentLoaded', function () {
Since the application is in React, can we just load this script from react? Do not think adding scripts to assets is a great approach.

2023-09-28 03:25 UTC, shakyaprasen commented
I will take additional look into the PR after it has been properly divided into manageable pieces.

2023-09-29 05:16 UTC, closed without merging