html-css-layout: Fix layout with small change in styling
leapfrogtechnology/frogtoberfest pull request #71
Opened 2023-09-28 11:33 UTC by ajaydangol014

2023-09-28 14:38 UTC, shakyaprasen requested changes

2023-09-28 14:38 UTC, shakyaprasen commented on src/components/SiteHeader.js
> +        window.addEventListener('scroll', () => {
can we remove event listeners too when the component unmounts? returning a function which does calls [removeEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/removeEventListener) should be sufficient.

2023-09-28 14:38 UTC, shakyaprasen commented on src/pages/Home/index.js
> +      const totalDaysRemaining = Math.floor(seconds / 86400);
can we move the numbers like 86400 and 3600 to a suitable constant like 30_DAYS, etc.

2023-09-28 14:38 UTC, shakyaprasen commented on src/pages/Home/index.js
> +        if (index != index2) {
better to use `!==` strict checking

2023-09-28 14:38 UTC, shakyaprasen commented on src/pages/Home/index.js
> +        case 'seconds':
you can move 'seconds', 'minutes' etc to a constant or an object so that someone can know the possible options easily.

2023-09-28 14:38 UTC, shakyaprasen commented on src/pages/Home/index.js
> +      minute2Element.textContent = totalMinuteRemaing % 10;
any reason we are directly modifying the text instead of using React states?

2023-09-28 14:38 UTC, shakyaprasen commented on src/pages/User/components/PullRequests/ShareButtons.js
>          href={`https://twitter.com/intent/tweet?text=My progress on frogtoberfest ${pullRequestCount} / ${TOTAL_PR_COUNT}&url=${HOSTNAME}/user/${username}&hashtags=frogtoberfest, frogtoberfest`}
move this to a constant.

2023-09-29 02:28 UTC, RikLakhe approved these changes

2023-09-29 03:14 UTC, shakyaprasen approved these changes

2023-09-29 04:08 UTC, shakyaprasen commented
Please fix build issues.

2023-09-29 05:15 UTC, merged